dt_user_security_login:
    path:     /login
    defaults: { _controller: DTUserBundle:Security:login }

dt_user_security_login_check:
    path:     /login_check
    defaults: { _controller: DTUserBundle:Security:check }

dt_user_security_logout:
    path:     /logout
    defaults: { _controller: DTUserBundle:Security:check }
